// Generated from: D:\FnOS_Sync\03_English\Vocabulary\G6 Voc\00.原始檔案及導出\G6_vocabulary_p1-p2.json
// Source total_count: 230; generated_count: 230
window.VOCABULARY_DATA = [
  {
    "sourceNo": 1,
    "word": "agree",
    "partOfSpeech": "v.",
    "chineseMeaning": "同意",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "To have the same idea or say yes to something.",
    "exampleSentence": "I agree with your answer in class today.",
    "phrase": "agree with",
    "phonicsHint": "a · gree"
  },
  {
    "sourceNo": 2,
    "word": "announce",
    "partOfSpeech": "v.",
    "chineseMeaning": "宣佈",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "To tell people something in a clear or official way.",
    "exampleSentence": "The teacher will announce the news after lunch.",
    "phrase": "announce the news",
    "phonicsHint": "an · nounce"
  },
  {
    "sourceNo": 3,
    "word": "arrive",
    "partOfSpeech": "v.",
    "chineseMeaning": "抵達",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "To get to a place.",
    "exampleSentence": "We arrive at school at eight o'clock.",
    "phrase": "arrive at",
    "phonicsHint": "ar · rive"
  },
  {
    "sourceNo": 4,
    "word": "apologize",
    "partOfSpeech": "v.",
    "chineseMeaning": "道歉",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "To say sorry for something.",
    "exampleSentence": "He apologized for being late to music class.",
    "phrase": "apologize for",
    "phonicsHint": "a · pol · o · gize"
  },
  {
    "sourceNo": 5,
    "word": "bend",
    "partOfSpeech": "v.",
    "chineseMeaning": "彎曲",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "To make something curve or not straight.",
    "exampleSentence": "Please bend down to pick up the pencil.",
    "phrase": "bend down",
    "phonicsHint": "b + end"
  },
  {
    "sourceNo": 6,
    "word": "borrow",
    "partOfSpeech": "v.",
    "chineseMeaning": "借",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "To take and use something that you will give back later.",
    "exampleSentence": "I borrow books from the library every Friday.",
    "phrase": "borrow from",
    "phonicsHint": "bor · row"
  },
  {
    "sourceNo": 7,
    "word": "bounce",
    "partOfSpeech": "v.&n.",
    "chineseMeaning": "彈力",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "To jump back after hitting a surface.",
    "exampleSentence": "The ball will bounce back from the wall.",
    "phrase": "bounce back",
    "phonicsHint": "b + ounce"
  },
  {
    "sourceNo": 8,
    "word": "check",
    "partOfSpeech": "v.",
    "chineseMeaning": "檢查",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "To look at something to make sure it is right.",
    "exampleSentence": "Please check your work before you finish.",
    "phrase": "check your work",
    "phonicsHint": "ch + eck"
  },
  {
    "sourceNo": 9,
    "word": "complete",
    "partOfSpeech": "adj.; v.",
    "chineseMeaning": "完全的; 完成",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "Whole, or to finish something.",
    "exampleSentence": "I complete a task before dinner every night.",
    "phrase": "complete a task",
    "phonicsHint": "com · plete"
  },
  {
    "sourceNo": 10,
    "word": "continue",
    "partOfSpeech": "v.",
    "chineseMeaning": "繼續",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "To keep doing something.",
    "exampleSentence": "Please continue to read the story after lunch.",
    "phrase": "continue to",
    "phonicsHint": "con · tin · ue"
  },
  {
    "sourceNo": 11,
    "word": "cover",
    "partOfSpeech": "n.; v.",
    "chineseMeaning": "掩蔽物；覆蓋",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "Something on top, or to put something over another thing.",
    "exampleSentence": "Cover the box with a cloth before painting.",
    "phrase": "cover with",
    "phonicsHint": "cov · er"
  },
  {
    "sourceNo": 12,
    "word": "describe",
    "partOfSpeech": "v.",
    "chineseMeaning": "描寫, 敘述",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "To tell what someone or something is like.",
    "exampleSentence": "Please describe the picture in detail to your partner.",
    "phrase": "describe in detail",
    "phonicsHint": "de · scribe"
  },
  {
    "sourceNo": 13,
    "word": "explain",
    "partOfSpeech": "v.",
    "chineseMeaning": "說明，解釋",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "To make something clear or easy to understand.",
    "exampleSentence": "Can you explain the game to me?",
    "phrase": "explain to",
    "phonicsHint": "ex · plain"
  },
  {
    "sourceNo": 14,
    "word": "enter",
    "partOfSpeech": "v.",
    "chineseMeaning": "進入, 進去",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "To go into a place.",
    "exampleSentence": "Please enter the room quietly before the lesson starts.",
    "phrase": "enter the room",
    "phonicsHint": "en · ter"
  },
  {
    "sourceNo": 15,
    "word": "fill",
    "partOfSpeech": "v.",
    "chineseMeaning": "裝滿，填滿",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "To make something full.",
    "exampleSentence": "Fill the bottle with water before soccer practice.",
    "phrase": "fill with",
    "phonicsHint": "f + ill"
  },
  {
    "sourceNo": 16,
    "word": "reach",
    "partOfSpeech": "v.",
    "chineseMeaning": "到達",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "To get to a place, point, or goal.",
    "exampleSentence": "Can you reach for the book on the shelf?",
    "phrase": "reach for",
    "phonicsHint": "r + each"
  },
  {
    "sourceNo": 17,
    "word": "receive",
    "partOfSpeech": "v.",
    "chineseMeaning": "收到, 接到",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "To get something from someone.",
    "exampleSentence": "I received a letter from my friend.",
    "phrase": "receive from",
    "phonicsHint": "re · ceive"
  },
  {
    "sourceNo": 18,
    "word": "return",
    "partOfSpeech": "v.",
    "chineseMeaning": "返回, 回來",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "To go or come back.",
    "exampleSentence": "We return to school after lunch every Monday.",
    "phrase": "return to",
    "phonicsHint": "re · turn"
  },
  {
    "sourceNo": 19,
    "word": "repeat",
    "partOfSpeech": "v.",
    "chineseMeaning": "重說",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "To say or do something again.",
    "exampleSentence": "Please repeat after me during English reading practice.",
    "phrase": "repeat after",
    "phonicsHint": "re · peat"
  },
  {
    "sourceNo": 20,
    "word": "remind",
    "partOfSpeech": "vt.",
    "chineseMeaning": "使想起",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "To help someone remember something.",
    "exampleSentence": "Please remind me to bring my book.",
    "phrase": "remind someone to",
    "phonicsHint": "re · mind"
  },
  {
    "sourceNo": 21,
    "word": "search",
    "partOfSpeech": "n.& v.",
    "chineseMeaning": "搜索, 尋找",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "To try to find someone or something.",
    "exampleSentence": "I search for my missing notebook after school.",
    "phrase": "search for",
    "phonicsHint": "s + earch"
  },
  {
    "sourceNo": 22,
    "word": "separate",
    "partOfSpeech": "v.; adj.",
    "chineseMeaning": "分離；分開的",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "To move things apart or keep them apart.",
    "exampleSentence": "Please separate the red cards from the blue cards.",
    "phrase": "separate from",
    "phonicsHint": "sep · a · rate"
  },
  {
    "sourceNo": 23,
    "word": "spend",
    "partOfSpeech": "v.",
    "chineseMeaning": "花（錢/時間）",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "To use time or money for something.",
    "exampleSentence": "I spend time with my family every Sunday.",
    "phrase": "spend time",
    "phonicsHint": "sp + end"
  },
  {
    "sourceNo": 24,
    "word": "report",
    "partOfSpeech": "n.& v.",
    "chineseMeaning": "報告；報導",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "To tell or write information about something.",
    "exampleSentence": "We write a report about animals in class.",
    "phrase": "write a report",
    "phonicsHint": "re · port"
  },
  {
    "sourceNo": 25,
    "word": "clap",
    "partOfSpeech": "v.",
    "chineseMeaning": "鼓掌，拍手",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "To hit your hands together to show you like something.",
    "exampleSentence": "The students clap for the singer after the song.",
    "phrase": "clap for",
    "phonicsHint": "cl + ap"
  },
  {
    "sourceNo": 26,
    "word": "rule",
    "partOfSpeech": "v.; n.",
    "chineseMeaning": "統治; 規則",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "An instruction people should follow, or to control.",
    "exampleSentence": "We follow the rule to keep everyone safe.",
    "phrase": "follow the rule",
    "phonicsHint": "r + ule"
  },
  {
    "sourceNo": 27,
    "word": "travel",
    "partOfSpeech": "v.&n.",
    "chineseMeaning": "旅行",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "To go from one place to another place.",
    "exampleSentence": "My family will travel to Japan next summer.",
    "phrase": "travel to",
    "phonicsHint": "trav · el"
  },
  {
    "sourceNo": 28,
    "word": "wish",
    "partOfSpeech": "v.; n.",
    "chineseMeaning": "希望；祝願",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "To hope for something you want.",
    "exampleSentence": "I wish for a new bike on my birthday.",
    "phrase": "wish for",
    "phonicsHint": "w + ish"
  },
  {
    "sourceNo": 29,
    "word": "work",
    "partOfSpeech": "v.&n.",
    "chineseMeaning": "工作",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "To do a job or activity.",
    "exampleSentence": "We work on the project after lunch today.",
    "phrase": "work on",
    "phonicsHint": "w + ork"
  },
  {
    "sourceNo": 30,
    "word": "cough",
    "partOfSpeech": "n.& v.",
    "chineseMeaning": "咳嗽",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "To push air out of your throat with a sound.",
    "exampleSentence": "I have a cough and need some warm water.",
    "phrase": "have a cough",
    "phonicsHint": "c + ough"
  },
  {
    "sourceNo": 31,
    "word": "headache",
    "partOfSpeech": "n.",
    "chineseMeaning": "頭疼",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "A pain in your head.",
    "exampleSentence": "I have a headache after reading for too long.",
    "phrase": "have a headache",
    "phonicsHint": "head · ache"
  },
  {
    "sourceNo": 32,
    "word": "present",
    "partOfSpeech": "v.; n.",
    "chineseMeaning": "呈現；禮物",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "To show something to others, or a gift.",
    "exampleSentence": "She will present her drawing to the class today.",
    "phrase": "present to",
    "phonicsHint": "pre · sent"
  },
  {
    "sourceNo": 33,
    "word": "schedule",
    "partOfSpeech": "v.; n.",
    "chineseMeaning": "安排；時間表",
    "categoryZh": "動詞",
    "categoryEn": "Verbs",
    "englishDefinition": "To plan when something will happen.",
    "exampleSentence": "We schedule a meeting with our teacher tomorrow.",
    "phrase": "schedule a meeting",
    "phonicsHint": "sched · ule"
  },
  {
    "sourceNo": 1,
    "word": "asleep",
    "partOfSpeech": "adj.",
    "chineseMeaning": "睡著的",
    "categoryZh": "形容詞",
    "categoryEn": "Adjectives",
    "englishDefinition": "Sleeping, not awake.",
    "exampleSentence": "I fall asleep after reading my favorite story.",
    "phrase": "fall asleep",
    "phonicsHint": "a · sleep"
  },
  {
    "sourceNo": 2,
    "word": "awake",
    "partOfSpeech": "adj.",
    "chineseMeaning": "醒著的",
    "categoryZh": "形容詞",
    "categoryEn": "Adjectives",
    "englishDefinition": "Not sleeping.",
    "exampleSentence": "I stay awake during the exciting movie tonight.",
    "phrase": "stay awake",
    "phonicsHint": "a · wake"
  },
  {
    "sourceNo": 3,
    "word": "brave",
    "partOfSpeech": "adj.",
    "chineseMeaning": "勇敢的",
    "categoryZh": "形容詞",
    "categoryEn": "Adjectives",
    "englishDefinition": "Ready to do something difficult or scary.",
    "exampleSentence": "She is brave enough to speak on stage.",
    "phrase": "brave enough",
    "phonicsHint": "br + ave"
  },
  {
    "sourceNo": 4,
    "word": "comfortable",
    "partOfSpeech": "adj.",
    "chineseMeaning": "感到舒服的",
    "categoryZh": "形容詞",
    "categoryEn": "Adjectives",
    "englishDefinition": "Feeling good and relaxed.",
    "exampleSentence": "This chair is comfortable enough for long reading.",
    "phrase": "comfortable enough",
    "phonicsHint": "com · fort · a · ble"
  },
  {
    "sourceNo": 5,
    "word": "curious",
    "partOfSpeech": "adj.",
    "chineseMeaning": "好奇的",
    "categoryZh": "形容詞",
    "categoryEn": "Adjectives",
    "englishDefinition": "Wanting to know or learn about something.",
    "exampleSentence": "I am curious about how plants grow bigger.",
    "phrase": "curious about",
    "phonicsHint": "cu · ri · ous"
  },
  {
    "sourceNo": 6,
    "word": "closed",
    "partOfSpeech": "adj.",
    "chineseMeaning": "關著的；不公開的",
    "categoryZh": "形容詞",
    "categoryEn": "Adjectives",
    "englishDefinition": "Not open.",
    "exampleSentence": "The library is closed during the school holiday.",
    "phrase": "be closed",
    "phonicsHint": "cl + osed"
  },
  {
    "sourceNo": 7,
    "word": "closing",
    "partOfSpeech": "adj.; n.",
    "chineseMeaning": "結束的；關閉",
    "categoryZh": "形容詞",
    "categoryEn": "Adjectives",
    "englishDefinition": "Coming at the end, or the act of shutting.",
    "exampleSentence": "The closing song makes everyone smile at school.",
    "phrase": "closing song",
    "phonicsHint": "clos · ing"
  },
  {
    "sourceNo": 8,
    "word": "difficult",
    "partOfSpeech": "adj.",
    "chineseMeaning": "困難的",
    "categoryZh": "形容詞",
    "categoryEn": "Adjectives",
    "englishDefinition": "Not easy to do or understand.",
    "exampleSentence": "This math problem is difficult for many students today.",
    "phrase": "be difficult for",
    "phonicsHint": "dif · fi · cult"
  },
  {
    "sourceNo": 9,
    "word": "different",
    "partOfSpeech": "adj.",
    "chineseMeaning": "不同的",
    "categoryZh": "形容詞",
    "categoryEn": "Adjectives",
    "englishDefinition": "Not the same as another thing.",
    "exampleSentence": "My answer is different from your answer today.",
    "phrase": "different from",
    "phonicsHint": "dif · fer · ent"
  },
  {
    "sourceNo": 10,
    "word": "dangerous",
    "partOfSpeech": "adj.",
    "chineseMeaning": "有危險的",
    "categoryZh": "形容詞",
    "categoryEn": "Adjectives",
    "englishDefinition": "Not safe; able to hurt someone.",
    "exampleSentence": "It is dangerous to run across the road.",
    "phrase": "be dangerous to",
    "phonicsHint": "dan · ger · ous"
  },
  {
    "sourceNo": 11,
    "word": "special",
    "partOfSpeech": "n.",
    "chineseMeaning": "特殊的",
    "categoryZh": "形容詞",
    "categoryEn": "Adjectives",
    "englishDefinition": "Different from normal, or important to someone.",
    "exampleSentence": "This card is special to my little sister.",
    "phrase": "special to",
    "phonicsHint": "spe · cial"
  },
  {
    "sourceNo": 12,
    "word": "dead",
    "partOfSpeech": "adj.",
    "chineseMeaning": "無生命的",
    "categoryZh": "形容詞",
    "categoryEn": "Adjectives",
    "englishDefinition": "No longer living or working.",
    "exampleSentence": "The plant is dead because it had no water.",
    "phrase": "be dead",
    "phonicsHint": "d + ead"
  },
  {
    "sourceNo": 13,
    "word": "friendly",
    "partOfSpeech": "adj.",
    "chineseMeaning": "友好的",
    "categoryZh": "形容詞",
    "categoryEn": "Adjectives",
    "englishDefinition": "Kind and nice to other people.",
    "exampleSentence": "Our new neighbor is friendly to everyone here.",
    "phrase": "friendly to",
    "phonicsHint": "friend · ly"
  },
  {
    "sourceNo": 14,
    "word": "finished",
    "partOfSpeech": "adj.",
    "chineseMeaning": "完成了的",
    "categoryZh": "形容詞",
    "categoryEn": "Adjectives",
    "englishDefinition": "Done or completed.",
    "exampleSentence": "I am finished with my homework before dinner.",
    "phrase": "be finished with",
    "phonicsHint": "fin · ished"
  },
  {
    "sourceNo": 15,
    "word": "opposite",
    "partOfSpeech": "adj.",
    "chineseMeaning": "相反的",
    "categoryZh": "形容詞",
    "categoryEn": "Adjectives",
    "englishDefinition": "Completely different, or across from something.",
    "exampleSentence": "The bus stop is opposite the school gate.",
    "phrase": "opposite the",
    "phonicsHint": "op · po · site"
  },
  {
    "sourceNo": 16,
    "word": "serious",
    "partOfSpeech": "adj.",
    "chineseMeaning": "嚴肅的,認真的",
    "categoryZh": "形容詞",
    "categoryEn": "Adjectives",
    "englishDefinition": "Not joking, or important and needing care.",
    "exampleSentence": "Please be serious about this important safety rule.",
    "phrase": "be serious about",
    "phonicsHint": "se · ri · ous"
  },
  {
    "sourceNo": 17,
    "word": "silent",
    "partOfSpeech": "adj.",
    "chineseMeaning": "沉默的",
    "categoryZh": "形容詞",
    "categoryEn": "Adjectives",
    "englishDefinition": "Not making any sound.",
    "exampleSentence": "The room is silent during the reading test.",
    "phrase": "be silent",
    "phonicsHint": "si · lent"
  },
  {
    "sourceNo": 18,
    "word": "stomachache",
    "partOfSpeech": "adj.",
    "chineseMeaning": "胃疼的",
    "categoryZh": "形容詞",
    "categoryEn": "Adjectives",
    "englishDefinition": "A pain in your stomach.",
    "exampleSentence": "I have a stomachache after eating too quickly.",
    "phrase": "have a stomachache",
    "phonicsHint": "stom · ach · ache"
  },
  {
    "sourceNo": 19,
    "word": "weak",
    "partOfSpeech": "adj.",
    "chineseMeaning": "虛弱的",
    "categoryZh": "形容詞",
    "categoryEn": "Adjectives",
    "englishDefinition": "Not strong.",
    "exampleSentence": "I feel weak after running for a long time.",
    "phrase": "feel weak",
    "phonicsHint": "w + eak"
  },
  {
    "sourceNo": 20,
    "word": "alone",
    "partOfSpeech": "adj.",
    "chineseMeaning": "單獨的",
    "categoryZh": "形容詞",
    "categoryEn": "Adjectives",
    "englishDefinition": "Without other people.",
    "exampleSentence": "I stay alone in the classroom after school.",
    "phrase": "stay alone",
    "phonicsHint": "a · lone"
  },
  {
    "sourceNo": 21,
    "word": "bright",
    "partOfSpeech": "adj.",
    "chineseMeaning": "光亮的",
    "categoryZh": "形容詞",
    "categoryEn": "Adjectives",
    "englishDefinition": "Full of light or easy to see.",
    "exampleSentence": "The room is bright in the morning sun.",
    "phrase": "be bright",
    "phonicsHint": "br + ight"
  },
  {
    "sourceNo": 22,
    "word": "loving",
    "partOfSpeech": "adj.",
    "chineseMeaning": "充滿愛的",
    "categoryZh": "形容詞",
    "categoryEn": "Adjectives",
    "englishDefinition": "Showing love and care.",
    "exampleSentence": "My grandmother is loving to every child here.",
    "phrase": "loving to",
    "phonicsHint": "lov · ing"
  },
  {
    "sourceNo": 23,
    "word": "fair",
    "partOfSpeech": "adj.",
    "chineseMeaning": "公平的",
    "categoryZh": "形容詞",
    "categoryEn": "Adjectives",
    "englishDefinition": "Right and equal for everyone.",
    "exampleSentence": "The teacher is fair to all students.",
    "phrase": "fair to",
    "phonicsHint": "f + air"
  },
  {
    "sourceNo": 24,
    "word": "excellent",
    "partOfSpeech": "adj.",
    "chineseMeaning": "優秀的",
    "categoryZh": "形容詞",
    "categoryEn": "Adjectives",
    "englishDefinition": "Very good.",
    "exampleSentence": "She did an excellent job on the poster.",
    "phrase": "excellent job",
    "phonicsHint": "ex · cel · lent"
  },
  {
    "sourceNo": 25,
    "word": "excited",
    "partOfSpeech": "adj.",
    "chineseMeaning": "興奮的",
    "categoryZh": "形容詞",
    "categoryEn": "Adjectives",
    "englishDefinition": "Very happy and interested about something.",
    "exampleSentence": "I am excited about the school trip tomorrow.",
    "phrase": "excited about",
    "phonicsHint": "ex · cit · ed"
  },
  {
    "sourceNo": 26,
    "word": "exciting",
    "partOfSpeech": "adj.",
    "chineseMeaning": "令人興奮的",
    "categoryZh": "形容詞",
    "categoryEn": "Adjectives",
    "englishDefinition": "Making people feel very interested or happy.",
    "exampleSentence": "The game is exciting for everyone in class.",
    "phrase": "exciting for",
    "phonicsHint": "ex · cit · ing"
  },
  {
    "sourceNo": 27,
    "word": "silly",
    "partOfSpeech": "adj.",
    "chineseMeaning": "愚蠢的",
    "categoryZh": "形容詞",
    "categoryEn": "Adjectives",
    "englishDefinition": "Not wise or not serious.",
    "exampleSentence": "It is silly to wear socks on your hands.",
    "phrase": "be silly to",
    "phonicsHint": "sil · ly"
  },
  {
    "sourceNo": 28,
    "word": "square",
    "partOfSpeech": "adj.",
    "chineseMeaning": "正方形的",
    "categoryZh": "形容詞",
    "categoryEn": "Adjectives",
    "englishDefinition": "Having four equal sides and four corners.",
    "exampleSentence": "The window has a square shape in the picture.",
    "phrase": "square shape",
    "phonicsHint": "squ + are"
  },
  {
    "sourceNo": 29,
    "word": "round",
    "partOfSpeech": "adj.; n.",
    "chineseMeaning": "圓形的；圓形物",
    "categoryZh": "形容詞",
    "categoryEn": "Adjectives",
    "englishDefinition": "Shaped like a circle or a ball.",
    "exampleSentence": "We sit at the round table during art class.",
    "phrase": "round table",
    "phonicsHint": "r + ound"
  },
  {
    "sourceNo": 30,
    "word": "glad",
    "partOfSpeech": "adj.",
    "chineseMeaning": "高興的",
    "categoryZh": "形容詞",
    "categoryEn": "Adjectives",
    "englishDefinition": "Happy or pleased about something.",
    "exampleSentence": "I am glad to help my friend after school.",
    "phrase": "glad to",
    "phonicsHint": "gl + ad"
  },
  {
    "sourceNo": 31,
    "word": "far",
    "partOfSpeech": "adj.",
    "chineseMeaning": "遠的",
    "categoryZh": "形容詞",
    "categoryEn": "Adjectives",
    "englishDefinition": "A long distance away from a place.",
    "exampleSentence": "My home is far from school on rainy days.",
    "phrase": "far from",
    "phonicsHint": "f + ar"
  },
  {
    "sourceNo": 32,
    "word": "crazy",
    "partOfSpeech": "adj.",
    "chineseMeaning": "瘋狂的",
    "categoryZh": "形容詞",
    "categoryEn": "Adjectives",
    "englishDefinition": "Very strange, wild, or full of energy.",
    "exampleSentence": "The class had a crazy idea for the show.",
    "phrase": "crazy idea",
    "phonicsHint": "cra · zy"
  },
  {
    "sourceNo": 1,
    "word": "against",
    "partOfSpeech": "prep.",
    "chineseMeaning": "反對",
    "categoryZh": "介系詞",
    "categoryEn": "Preposition",
    "englishDefinition": "Not agreeing with someone or facing something.",
    "exampleSentence": "Our team played against the other class today.",
    "phrase": "play against",
    "phonicsHint": "a · gainst"
  },
  {
    "sourceNo": 2,
    "word": "along",
    "partOfSpeech": "prep.",
    "chineseMeaning": "沿著",
    "categoryZh": "介系詞",
    "categoryEn": "Preposition",
    "englishDefinition": "Moving beside or following the length of something.",
    "exampleSentence": "We walked along the river after lunch today.",
    "phrase": "walk along",
    "phonicsHint": "a · long"
  },
  {
    "sourceNo": 3,
    "word": "except",
    "partOfSpeech": "prep.",
    "chineseMeaning": "除…之外",
    "categoryZh": "介系詞",
    "categoryEn": "Preposition",
    "englishDefinition": "Not including someone or something.",
    "exampleSentence": "Everyone came to practice except Tom and Lisa.",
    "phrase": "everyone except",
    "phonicsHint": "ex · cept"
  },
  {
    "sourceNo": 4,
    "word": "since",
    "partOfSpeech": "prep.",
    "chineseMeaning": "自......以後",
    "categoryZh": "介系詞",
    "categoryEn": "Preposition",
    "englishDefinition": "From a time in the past until now.",
    "exampleSentence": "I have liked music since I was little.",
    "phrase": "since I was",
    "phonicsHint": "s + ince"
  },
  {
    "sourceNo": 1,
    "word": "either",
    "partOfSpeech": "pron.& adj.",
    "chineseMeaning": "(兩者中)任一",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "One or the other of two choices.",
    "exampleSentence": "You can choose either one for the game.",
    "phrase": "either one",
    "phonicsHint": "ei · ther"
  },
  {
    "sourceNo": 2,
    "word": "hers",
    "partOfSpeech": "pron.",
    "chineseMeaning": "她的",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "Belonging to a girl or woman already mentioned.",
    "exampleSentence": "This blue notebook is hers, not mine.",
    "phrase": "is hers",
    "phonicsHint": "h + ers"
  },
  {
    "sourceNo": 3,
    "word": "mine",
    "partOfSpeech": "pron.",
    "chineseMeaning": "我的（所有格代名詞）",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "Belonging to me.",
    "exampleSentence": "That red pencil is mine, so please return it.",
    "phrase": "is mine",
    "phonicsHint": "m + ine"
  },
  {
    "sourceNo": 4,
    "word": "nothing",
    "partOfSpeech": "pron.",
    "chineseMeaning": "沒有東西",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "Not anything; no thing.",
    "exampleSentence": "There is nothing to do before the bell rings.",
    "phrase": "nothing to do",
    "phonicsHint": "no · thing"
  },
  {
    "sourceNo": 5,
    "word": "none",
    "partOfSpeech": "pron.",
    "chineseMeaning": "沒有人/物",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "Not one of a group or amount.",
    "exampleSentence": "None of them wanted to miss the school trip.",
    "phrase": "none of them",
    "phonicsHint": "n + one"
  },
  {
    "sourceNo": 6,
    "word": "nobody",
    "partOfSpeech": "pron.",
    "chineseMeaning": "無人",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "No person; not anyone.",
    "exampleSentence": "Nobody in our group forgot the homework today.",
    "phrase": "nobody in",
    "phonicsHint": "no · bod · y"
  },
  {
    "sourceNo": 7,
    "word": "ours",
    "partOfSpeech": "pron.",
    "chineseMeaning": "我們的（名詞性物主代詞）",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "Belonging to us.",
    "exampleSentence": "The clean classroom is ours after we decorated it.",
    "phrase": "is ours",
    "phonicsHint": "our + s"
  },
  {
    "sourceNo": 8,
    "word": "ourselves",
    "partOfSpeech": "pron.",
    "chineseMeaning": "我們自己",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "We or us without help from other people.",
    "exampleSentence": "We made the poster by ourselves after class.",
    "phrase": "by ourselves",
    "phonicsHint": "our · selves"
  },
  {
    "sourceNo": 9,
    "word": "somebody",
    "partOfSpeech": "pron.",
    "chineseMeaning": "某人",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "A person, but you do not say who.",
    "exampleSentence": "Somebody left a lunch box near the door.",
    "phrase": "somebody left",
    "phonicsHint": "some · bod · y"
  },
  {
    "sourceNo": 10,
    "word": "someone",
    "partOfSpeech": "pron.",
    "chineseMeaning": "某人",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "A person, but you do not know or say who.",
    "exampleSentence": "Someone called my name across the playground today.",
    "phrase": "someone called",
    "phonicsHint": "some · one"
  },
  {
    "sourceNo": 11,
    "word": "something",
    "partOfSpeech": "pron.",
    "chineseMeaning": "某事",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "A thing, idea, or event that is not named.",
    "exampleSentence": "I want something warm to drink after swimming.",
    "phrase": "something warm",
    "phonicsHint": "some · thing"
  },
  {
    "sourceNo": 12,
    "word": "yours",
    "partOfSpeech": "pron.",
    "chineseMeaning": "你（們）的",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "Belonging to you.",
    "exampleSentence": "This seat is yours if you want it.",
    "phrase": "is yours",
    "phonicsHint": "your + s"
  },
  {
    "sourceNo": 13,
    "word": "yourself",
    "partOfSpeech": "pron.",
    "chineseMeaning": "你自己",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "You without help from another person.",
    "exampleSentence": "You can finish the puzzle by yourself today.",
    "phrase": "by yourself",
    "phonicsHint": "your · self"
  },
  {
    "sourceNo": 14,
    "word": "her",
    "partOfSpeech": "pron.",
    "chineseMeaning": "(受格)她;(所有格)她的",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "Used for a girl or woman as the object, or to show belonging.",
    "exampleSentence": "I gave her a pencil during English class.",
    "phrase": "gave her",
    "phonicsHint": "h + er"
  },
  {
    "sourceNo": 15,
    "word": "him",
    "partOfSpeech": "pron.",
    "chineseMeaning": "(受格)他",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "Used for a boy or man as the object.",
    "exampleSentence": "The teacher asked him to read the sentence.",
    "phrase": "asked him",
    "phonicsHint": "h + im"
  },
  {
    "sourceNo": 16,
    "word": "its",
    "partOfSpeech": "det.",
    "chineseMeaning": "它的",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "Belonging to an animal, thing, or place.",
    "exampleSentence": "The dog wagged its tail when we came home.",
    "phrase": "its tail",
    "phonicsHint": "it + s"
  },
  {
    "sourceNo": 17,
    "word": "me",
    "partOfSpeech": "pron.",
    "chineseMeaning": "我（受格）",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "Used when someone is talking about the speaker as the object.",
    "exampleSentence": "My sister helped me carry the heavy bag.",
    "phrase": "helped me",
    "phonicsHint": "m + e"
  },
  {
    "sourceNo": 18,
    "word": "our",
    "partOfSpeech": "pron.",
    "chineseMeaning": "我們的",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "Belonging to us.",
    "exampleSentence": "Our class cleaned the library before lunch today.",
    "phrase": "our class",
    "phonicsHint": "our"
  },
  {
    "sourceNo": 19,
    "word": "their",
    "partOfSpeech": "det.",
    "chineseMeaning": "他們的",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "Belonging to them.",
    "exampleSentence": "Their team practiced hard before the final game.",
    "phrase": "their team",
    "phonicsHint": "th + eir"
  },
  {
    "sourceNo": 20,
    "word": "them",
    "partOfSpeech": "pron.",
    "chineseMeaning": "他們",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "Used for people or things as the object.",
    "exampleSentence": "I helped them carry boxes to the classroom.",
    "phrase": "helped them",
    "phonicsHint": "th + em"
  },
  {
    "sourceNo": 21,
    "word": "these",
    "partOfSpeech": "det. & pron.",
    "chineseMeaning": "這些",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "The people or things near us now.",
    "exampleSentence": "These books belong on the top shelf.",
    "phrase": "these books",
    "phonicsHint": "th + ese"
  },
  {
    "sourceNo": 22,
    "word": "they",
    "partOfSpeech": "pron.",
    "chineseMeaning": "他們",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "Used to talk about people, animals, or things already mentioned.",
    "exampleSentence": "They arrived early for the science fair today.",
    "phrase": "they arrived",
    "phonicsHint": "th + ey"
  },
  {
    "sourceNo": 23,
    "word": "those",
    "partOfSpeech": "det. & pron.",
    "chineseMeaning": "那些",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "The people or things farther away from us.",
    "exampleSentence": "Those shoes by the door are not mine.",
    "phrase": "those shoes",
    "phonicsHint": "th + ose"
  },
  {
    "sourceNo": 24,
    "word": "us",
    "partOfSpeech": "pron.",
    "chineseMeaning": "我們",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "Used for we as the object.",
    "exampleSentence": "The coach taught us a new game today.",
    "phrase": "taught us",
    "phonicsHint": "u + s"
  },
  {
    "sourceNo": 25,
    "word": "we",
    "partOfSpeech": "pron.",
    "chineseMeaning": "我們",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "Used when the speaker talks about a group including themselves.",
    "exampleSentence": "We worked together to finish the project early.",
    "phrase": "we worked",
    "phonicsHint": "w + e"
  },
  {
    "sourceNo": 26,
    "word": "whose",
    "partOfSpeech": "det.&pron.",
    "chineseMeaning": "誰的",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "Used to ask or say which person something belongs to.",
    "exampleSentence": "Whose bag is on the chair near the window?",
    "phrase": "whose bag",
    "phonicsHint": "wh + ose"
  },
  {
    "sourceNo": 27,
    "word": "anything",
    "partOfSpeech": "pron.",
    "chineseMeaning": "任何事",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "Any thing, often used in questions or negative sentences.",
    "exampleSentence": "Do you need anything else before we leave?",
    "phrase": "anything else",
    "phonicsHint": "an · y · thing"
  },
  {
    "sourceNo": 28,
    "word": "anybody",
    "partOfSpeech": "pron.",
    "chineseMeaning": "任何人",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "Any person, often used in questions or negative sentences.",
    "exampleSentence": "Can anybody help me move this table?",
    "phrase": "anybody help",
    "phonicsHint": "an · y · bod · y"
  },
  {
    "sourceNo": 29,
    "word": "anyone",
    "partOfSpeech": "pron.",
    "chineseMeaning": "任何人",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "Any person; anybody.",
    "exampleSentence": "Did anyone see my ruler after art class?",
    "phrase": "anyone see",
    "phonicsHint": "an · y · one"
  },
  {
    "sourceNo": 30,
    "word": "everybody",
    "partOfSpeech": "pron.",
    "chineseMeaning": "每人",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "Every person in a group.",
    "exampleSentence": "Everybody listened carefully during the safety lesson today.",
    "phrase": "everybody listened",
    "phonicsHint": "ev · ery · bod · y"
  },
  {
    "sourceNo": 31,
    "word": "everyone",
    "partOfSpeech": "pron.",
    "chineseMeaning": "每人",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "Every person; everybody.",
    "exampleSentence": "Everyone brought a notebook to English class today.",
    "phrase": "everyone brought",
    "phonicsHint": "ev · ery · one"
  },
  {
    "sourceNo": 32,
    "word": "everything",
    "partOfSpeech": "pron.",
    "chineseMeaning": "每件事",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "All things in a group or situation.",
    "exampleSentence": "Everything in my desk is neat and ready.",
    "phrase": "everything in",
    "phonicsHint": "ev · ery · thing"
  },
  {
    "sourceNo": 33,
    "word": "everywhere",
    "partOfSpeech": "adv.&pron.&conj.",
    "chineseMeaning": "到處",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "In, at, or to every place.",
    "exampleSentence": "We looked everywhere for the missing library card.",
    "phrase": "looked everywhere",
    "phonicsHint": "ev · ery · where"
  },
  {
    "sourceNo": 34,
    "word": "herself",
    "partOfSpeech": "pron.",
    "chineseMeaning": "她自己",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "She or her without help from another person.",
    "exampleSentence": "She finished the drawing by herself after dinner.",
    "phrase": "by herself",
    "phonicsHint": "her · self"
  },
  {
    "sourceNo": 35,
    "word": "himself",
    "partOfSpeech": "pron.",
    "chineseMeaning": "他自己",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "He or him without help from another person.",
    "exampleSentence": "He fixed the model by himself at home.",
    "phrase": "by himself",
    "phonicsHint": "him · self"
  },
  {
    "sourceNo": 36,
    "word": "myself",
    "partOfSpeech": "pron.",
    "chineseMeaning": "我自己",
    "categoryZh": "代名詞",
    "categoryEn": "Pronoun",
    "englishDefinition": "I or me without help from another person.",
    "exampleSentence": "I packed my school bag by myself today.",
    "phrase": "by myself",
    "phonicsHint": "my · self"
  },
  {
    "sourceNo": 1,
    "word": "absolutely",
    "partOfSpeech": "adv.",
    "chineseMeaning": "完全地",
    "categoryZh": "副詞",
    "categoryEn": "Adverb",
    "englishDefinition": "Completely or very strongly.",
    "exampleSentence": "I am absolutely sure about my answer today.",
    "phrase": "absolutely sure",
    "phonicsHint": "ab · so · lute · ly"
  },
  {
    "sourceNo": 2,
    "word": "afterward(s)",
    "partOfSpeech": "adv.",
    "chineseMeaning": "後來地",
    "categoryZh": "副詞",
    "categoryEn": "Adverb",
    "englishDefinition": "At a later time; after something happens.",
    "exampleSentence": "We ate lunch and played basketball afterwards outside.",
    "phrase": "afterwards outside",
    "phonicsHint": "af · ter · wards"
  },
  {
    "sourceNo": 3,
    "word": "almost*",
    "partOfSpeech": "adv.",
    "chineseMeaning": "幾乎",
    "categoryZh": "副詞",
    "categoryEn": "Adverb",
    "englishDefinition": "Nearly, but not completely.",
    "exampleSentence": "I almost finished my homework before dinner tonight.",
    "phrase": "almost finished",
    "phonicsHint": "al · most"
  },
  {
    "sourceNo": 4,
    "word": "already",
    "partOfSpeech": "adv.",
    "chineseMeaning": "已經",
    "categoryZh": "副詞",
    "categoryEn": "Adverb",
    "englishDefinition": "Before now or before a certain time.",
    "exampleSentence": "She has already read that story twice this week.",
    "phrase": "already read",
    "phonicsHint": "al · read · y"
  },
  {
    "sourceNo": 5,
    "word": "ahead",
    "partOfSpeech": "adv.",
    "chineseMeaning": "向前",
    "categoryZh": "副詞",
    "categoryEn": "Adverb",
    "englishDefinition": "In front or forward in space or time.",
    "exampleSentence": "Please walk ahead of me on the path.",
    "phrase": "walk ahead",
    "phonicsHint": "a · head"
  },
  {
    "sourceNo": 6,
    "word": "completely",
    "partOfSpeech": "adv.",
    "chineseMeaning": "完全地",
    "categoryZh": "副詞",
    "categoryEn": "Adverb",
    "englishDefinition": "In every way or as much as possible.",
    "exampleSentence": "The room was completely quiet during the test today.",
    "phrase": "completely quiet",
    "phonicsHint": "com · plete · ly"
  },
  {
    "sourceNo": 7,
    "word": "differently",
    "partOfSpeech": "adv.",
    "chineseMeaning": "不同地",
    "categoryZh": "副詞",
    "categoryEn": "Adverb",
    "englishDefinition": "In another way, not the same way.",
    "exampleSentence": "We solved the math problem differently this time.",
    "phrase": "solve differently",
    "phonicsHint": "dif · fer · ent · ly"
  },
  {
    "sourceNo": 8,
    "word": "else",
    "partOfSpeech": "adv.; adj.",
    "chineseMeaning": "另外；別的",
    "categoryZh": "副詞",
    "categoryEn": "Adverb",
    "englishDefinition": "Other or more than the thing mentioned.",
    "exampleSentence": "Do you want anything else for your lunch?",
    "phrase": "anything else",
    "phonicsHint": "e + lse"
  },
  {
    "sourceNo": 9,
    "word": "sincerely",
    "partOfSpeech": "adv.",
    "chineseMeaning": "真誠地",
    "categoryZh": "副詞",
    "categoryEn": "Adverb",
    "englishDefinition": "In an honest and true way.",
    "exampleSentence": "She sincerely thanked her teacher after the concert.",
    "phrase": "sincerely thanked",
    "phonicsHint": "sin · cere · ly"
  },
  {
    "sourceNo": 10,
    "word": "suddenly",
    "partOfSpeech": "adv.",
    "chineseMeaning": "突然",
    "categoryZh": "副詞",
    "categoryEn": "Adverb",
    "englishDefinition": "Quickly and without warning.",
    "exampleSentence": "The lights suddenly went out during the storm.",
    "phrase": "suddenly went",
    "phonicsHint": "sud · den · ly"
  },
  {
    "sourceNo": 11,
    "word": "yet",
    "partOfSpeech": "adv.",
    "chineseMeaning": "還",
    "categoryZh": "副詞",
    "categoryEn": "Adverb",
    "englishDefinition": "Up to now, or still not at this time.",
    "exampleSentence": "I have not finished my reading homework yet.",
    "phrase": "not yet",
    "phonicsHint": "y + et"
  },
  {
    "sourceNo": 1,
    "word": "baker",
    "partOfSpeech": "n.",
    "chineseMeaning": "烘焙師",
    "categoryZh": "職業",
    "categoryEn": "Occupation",
    "englishDefinition": "A person who makes bread, cakes, or cookies.",
    "exampleSentence": "The baker made fresh bread early this morning.",
    "phrase": "fresh bread",
    "phonicsHint": "bak · er"
  },
  {
    "sourceNo": 2,
    "word": "writer",
    "partOfSpeech": "n.",
    "chineseMeaning": "作家",
    "categoryZh": "職業",
    "categoryEn": "Occupation",
    "englishDefinition": "A person who writes books, stories, or articles.",
    "exampleSentence": "The writer shared a funny story with our class.",
    "phrase": "story writer",
    "phonicsHint": "writ · er"
  },
  {
    "sourceNo": 3,
    "word": "worker",
    "partOfSpeech": "n.",
    "chineseMeaning": "工人",
    "categoryZh": "職業",
    "categoryEn": "Occupation",
    "englishDefinition": "A person who does a job or task.",
    "exampleSentence": "The worker fixed the broken chair after school.",
    "phrase": "hard worker",
    "phonicsHint": "work · er"
  },
  {
    "sourceNo": 4,
    "word": "singer",
    "partOfSpeech": "n.",
    "chineseMeaning": "歌手",
    "categoryZh": "職業",
    "categoryEn": "Occupation",
    "englishDefinition": "A person who sings songs.",
    "exampleSentence": "The singer practiced a new song before dinner.",
    "phrase": "famous singer",
    "phonicsHint": "sing · er"
  },
  {
    "sourceNo": 5,
    "word": "pilot",
    "partOfSpeech": "n.",
    "chineseMeaning": "飛行員",
    "categoryZh": "職業",
    "categoryEn": "Occupation",
    "englishDefinition": "A person who flies an airplane.",
    "exampleSentence": "The pilot landed the airplane safely at night.",
    "phrase": "airplane pilot",
    "phonicsHint": "pi · lot"
  },
  {
    "sourceNo": 6,
    "word": "doctor",
    "partOfSpeech": "n.",
    "chineseMeaning": "醫生；博士",
    "categoryZh": "職業",
    "categoryEn": "Occupation",
    "englishDefinition": "A person who helps sick or hurt people.",
    "exampleSentence": "The doctor checked my throat at the clinic.",
    "phrase": "see a doctor",
    "phonicsHint": "doc · tor"
  },
  {
    "sourceNo": 7,
    "word": "farmer",
    "partOfSpeech": "n.",
    "chineseMeaning": "農夫",
    "categoryZh": "職業",
    "categoryEn": "Occupation",
    "englishDefinition": "A person who grows food or takes care of farm animals.",
    "exampleSentence": "The farmer grows vegetables near the small town.",
    "phrase": "vegetable farmer",
    "phonicsHint": "farm · er"
  },
  {
    "sourceNo": 8,
    "word": "actor",
    "partOfSpeech": "n.",
    "chineseMeaning": "演員",
    "categoryZh": "職業",
    "categoryEn": "Occupation",
    "englishDefinition": "A man or boy who acts in a play, movie, or show.",
    "exampleSentence": "The actor remembered every line in the school play.",
    "phrase": "movie actor",
    "phonicsHint": "ac · tor"
  },
  {
    "sourceNo": 9,
    "word": "actress",
    "partOfSpeech": "n.",
    "chineseMeaning": "女演員",
    "categoryZh": "職業",
    "categoryEn": "Occupation",
    "englishDefinition": "A woman or girl who acts in a play, movie, or show.",
    "exampleSentence": "The actress smiled brightly after the final scene.",
    "phrase": "young actress",
    "phonicsHint": "ac · tress"
  },
  {
    "sourceNo": 10,
    "word": "artist",
    "partOfSpeech": "n.",
    "chineseMeaning": "藝術家",
    "categoryZh": "職業",
    "categoryEn": "Occupation",
    "englishDefinition": "A person who makes art, such as pictures or music.",
    "exampleSentence": "The artist painted a bright picture for school.",
    "phrase": "young artist",
    "phonicsHint": "art · ist"
  },
  {
    "sourceNo": 11,
    "word": "chef",
    "partOfSpeech": "n.",
    "chineseMeaning": "〈法〉廚師",
    "categoryZh": "職業",
    "categoryEn": "Occupation",
    "englishDefinition": "A person whose job is cooking food.",
    "exampleSentence": "The chef cooked vegetable soup for the students.",
    "phrase": "head chef",
    "phonicsHint": "ch + ef"
  },
  {
    "sourceNo": 12,
    "word": "dentist",
    "partOfSpeech": "n.",
    "chineseMeaning": "牙醫",
    "categoryZh": "職業",
    "categoryEn": "Occupation",
    "englishDefinition": "A person whose job is taking care of teeth.",
    "exampleSentence": "The dentist cleaned my teeth after lunch today.",
    "phrase": "visit the dentist",
    "phonicsHint": "den · tist"
  },
  {
    "sourceNo": 13,
    "word": "driver",
    "partOfSpeech": "n.",
    "chineseMeaning": "駕駛員",
    "categoryZh": "職業",
    "categoryEn": "Occupation",
    "englishDefinition": "A person who drives a car, bus, or truck.",
    "exampleSentence": "The driver stopped the bus near our school.",
    "phrase": "bus driver",
    "phonicsHint": "driv · er"
  },
  {
    "sourceNo": 14,
    "word": "firefighter",
    "partOfSpeech": "n.",
    "chineseMeaning": "消防隊員",
    "categoryZh": "職業",
    "categoryEn": "Occupation",
    "englishDefinition": "A person whose job is stopping fires and helping people.",
    "exampleSentence": "The firefighter taught us about safety at school.",
    "phrase": "brave firefighter",
    "phonicsHint": "fire · fight · er"
  },
  {
    "sourceNo": 15,
    "word": "librarian",
    "partOfSpeech": "n.",
    "chineseMeaning": "圖書館館員",
    "categoryZh": "職業",
    "categoryEn": "Occupation",
    "englishDefinition": "A person who works in a library.",
    "exampleSentence": "The librarian helped me find a science book.",
    "phrase": "school librarian",
    "phonicsHint": "li · brar · i · an"
  },
  {
    "sourceNo": 16,
    "word": "nurse",
    "partOfSpeech": "n.",
    "chineseMeaning": "護士",
    "categoryZh": "職業",
    "categoryEn": "Occupation",
    "englishDefinition": "A person who helps doctors care for sick people.",
    "exampleSentence": "The nurse gave me water after the checkup.",
    "phrase": "kind nurse",
    "phonicsHint": "n + urse"
  },
  {
    "sourceNo": 17,
    "word": "scientist",
    "partOfSpeech": "n.",
    "chineseMeaning": "科學家",
    "categoryZh": "職業",
    "categoryEn": "Occupation",
    "englishDefinition": "A person who studies science and learns how things work.",
    "exampleSentence": "The scientist tested the water in the classroom.",
    "phrase": "young scientist",
    "phonicsHint": "sci · en · tist"
  },
  {
    "sourceNo": 18,
    "word": "dancer",
    "partOfSpeech": "n.",
    "chineseMeaning": "舞蹈演員",
    "categoryZh": "職業",
    "categoryEn": "Occupation",
    "englishDefinition": "A person who dances for work or practice.",
    "exampleSentence": "The dancer moved gracefully across the stage tonight.",
    "phrase": "ballet dancer",
    "phonicsHint": "danc · er"
  },
  {
    "sourceNo": 1,
    "word": "and",
    "partOfSpeech": "conj.",
    "chineseMeaning": "和",
    "categoryZh": "連接詞",
    "categoryEn": "Conjunction",
    "englishDefinition": "Used to join words or ideas together.",
    "exampleSentence": "I packed pencils and notebooks for school today.",
    "phrase": "and notebooks",
    "phonicsHint": "a + nd"
  },
  {
    "sourceNo": 2,
    "word": "as",
    "partOfSpeech": "conj.",
    "chineseMeaning": "像...一樣，作為",
    "categoryZh": "連接詞",
    "categoryEn": "Conjunction",
    "englishDefinition": "Used to compare things or show a role.",
    "exampleSentence": "She dressed as a doctor for career day.",
    "phrase": "as a doctor",
    "phonicsHint": "a + s"
  },
  {
    "sourceNo": 3,
    "word": "because",
    "partOfSpeech": "conj.",
    "chineseMeaning": "因為",
    "categoryZh": "連接詞",
    "categoryEn": "Conjunction",
    "englishDefinition": "Used to give a reason.",
    "exampleSentence": "I stayed home because I had a fever.",
    "phrase": "because I",
    "phonicsHint": "be · cause"
  },
  {
    "sourceNo": 4,
    "word": "but",
    "partOfSpeech": "conj.",
    "chineseMeaning": "但是",
    "categoryZh": "連接詞",
    "categoryEn": "Conjunction",
    "englishDefinition": "Used to show a different or opposite idea.",
    "exampleSentence": "The question looked easy, but I read carefully.",
    "phrase": "but I",
    "phonicsHint": "b + ut"
  },
  {
    "sourceNo": 5,
    "word": "if",
    "partOfSpeech": "conj.",
    "chineseMeaning": "如果",
    "categoryZh": "連接詞",
    "categoryEn": "Conjunction",
    "englishDefinition": "Used to talk about something that may happen.",
    "exampleSentence": "If it rains tomorrow, we will stay inside.",
    "phrase": "if it rains",
    "phonicsHint": "i + f"
  },
  {
    "sourceNo": 6,
    "word": "or",
    "partOfSpeech": "conj.",
    "chineseMeaning": "或者",
    "categoryZh": "連接詞",
    "categoryEn": "Conjunction",
    "englishDefinition": "Used to show a choice between things.",
    "exampleSentence": "Would you like milk or juice with lunch?",
    "phrase": "or juice",
    "phonicsHint": "o + r"
  },
  {
    "sourceNo": 7,
    "word": "while",
    "partOfSpeech": "conj.",
    "chineseMeaning": "當......的時候",
    "categoryZh": "連接詞",
    "categoryEn": "Conjunction",
    "englishDefinition": "During the time that something is happening.",
    "exampleSentence": "I listened to music while I cleaned my room.",
    "phrase": "while I",
    "phonicsHint": "wh + ile"
  },
  {
    "sourceNo": 1,
    "word": "world",
    "partOfSpeech": "n.",
    "chineseMeaning": "世界",
    "categoryZh": "洲別",
    "categoryEn": "Continents",
    "englishDefinition": "The earth and all the people and places on it.",
    "exampleSentence": "Children around the world learn many different languages.",
    "phrase": "around the world",
    "phonicsHint": "w + orld"
  },
  {
    "sourceNo": 2,
    "word": "Australia",
    "partOfSpeech": "n.",
    "chineseMeaning": "澳洲",
    "categoryZh": "洲別",
    "categoryEn": "Continents",
    "englishDefinition": "A large country and continent in the Southern Hemisphere.",
    "exampleSentence": "My cousin visited Australia during her summer vacation.",
    "phrase": "visit Australia",
    "phonicsHint": "Aus · tra · li · a"
  },
  {
    "sourceNo": 3,
    "word": "Africa",
    "partOfSpeech": "n.",
    "chineseMeaning": "非洲",
    "categoryZh": "洲別",
    "categoryEn": "Continents",
    "englishDefinition": "A large continent with many countries.",
    "exampleSentence": "Africa has many countries, languages, and beautiful places.",
    "phrase": "in Africa",
    "phonicsHint": "Af · ri · ca"
  },
  {
    "sourceNo": 4,
    "word": "Asia",
    "partOfSpeech": "n.",
    "chineseMeaning": "亞洲",
    "categoryZh": "洲別",
    "categoryEn": "Continents",
    "englishDefinition": "The largest continent in the world.",
    "exampleSentence": "Many students in Asia study English at school.",
    "phrase": "in Asia",
    "phonicsHint": "A · sia"
  },
  {
    "sourceNo": 5,
    "word": "Asian",
    "partOfSpeech": "adj.",
    "chineseMeaning": "亞洲的；亞洲人的",
    "categoryZh": "洲別",
    "categoryEn": "Continents",
    "englishDefinition": "From or related to Asia or its people.",
    "exampleSentence": "We learned about Asian food during culture week.",
    "phrase": "Asian food",
    "phonicsHint": "A · sian"
  },
  {
    "sourceNo": 6,
    "word": "Europe",
    "partOfSpeech": "n.",
    "chineseMeaning": "歐洲",
    "categoryZh": "洲別",
    "categoryEn": "Continents",
    "englishDefinition": "A continent with many countries such as France and Germany.",
    "exampleSentence": "Europe has many old cities and famous museums.",
    "phrase": "in Europe",
    "phonicsHint": "Eu · rope"
  },
  {
    "sourceNo": 7,
    "word": "America",
    "partOfSpeech": "n.",
    "chineseMeaning": "美國，美洲",
    "categoryZh": "洲別",
    "categoryEn": "Continents",
    "englishDefinition": "The United States, or the continents of North and South America.",
    "exampleSentence": "My aunt lives in America with her family.",
    "phrase": "in America",
    "phonicsHint": "A · mer · i · ca"
  },
  {
    "sourceNo": 1,
    "word": "France",
    "partOfSpeech": "n.",
    "chineseMeaning": "法國",
    "categoryZh": "國家",
    "categoryEn": "Country",
    "englishDefinition": "A country in Europe known for Paris.",
    "exampleSentence": "France is famous for art, bread, and museums.",
    "phrase": "visit France",
    "phonicsHint": "Fr + ance"
  },
  {
    "sourceNo": 2,
    "word": "Germany",
    "partOfSpeech": "n.",
    "chineseMeaning": "德國",
    "categoryZh": "國家",
    "categoryEn": "Country",
    "englishDefinition": "A country in Europe known for Berlin.",
    "exampleSentence": "Germany has many castles, forests, and busy cities.",
    "phrase": "visit Germany",
    "phonicsHint": "Ger · ma · ny"
  },
  {
    "sourceNo": 3,
    "word": "Japan",
    "partOfSpeech": "n.",
    "chineseMeaning": "日本",
    "categoryZh": "國家",
    "categoryEn": "Country",
    "englishDefinition": "A country in Asia made of many islands.",
    "exampleSentence": "Japan has beautiful cherry blossoms in the spring.",
    "phrase": "visit Japan",
    "phonicsHint": "Ja · pan"
  },
  {
    "sourceNo": 4,
    "word": "India",
    "partOfSpeech": "n.",
    "chineseMeaning": "印度",
    "categoryZh": "國家",
    "categoryEn": "Country",
    "englishDefinition": "A large country in Asia.",
    "exampleSentence": "India has many languages, festivals, and colorful clothes.",
    "phrase": "in India",
    "phonicsHint": "In · di · a"
  },
  {
    "sourceNo": 5,
    "word": "UK (United Kingdom)",
    "partOfSpeech": "abbr.",
    "chineseMeaning": "英國",
    "categoryZh": "國家",
    "categoryEn": "Country",
    "englishDefinition": "The United Kingdom, a country made of four parts.",
    "exampleSentence": "The UK has England, Scotland, Wales, and Northern Ireland.",
    "phrase": "the UK",
    "phonicsHint": "U · K"
  },
  {
    "sourceNo": 6,
    "word": "U.S.(United States)",
    "partOfSpeech": "abbr.",
    "chineseMeaning": "美國",
    "categoryZh": "國家",
    "categoryEn": "Country",
    "englishDefinition": "The United States, a country in North America.",
    "exampleSentence": "The U.S. has many states and famous cities.",
    "phrase": "the U.S.",
    "phonicsHint": "U · S"
  },
  {
    "sourceNo": 7,
    "word": "Britain",
    "partOfSpeech": "n.",
    "chineseMeaning": "英國",
    "categoryZh": "國家",
    "categoryEn": "Country",
    "englishDefinition": "Another name often used for Great Britain.",
    "exampleSentence": "Britain has many old castles and busy towns.",
    "phrase": "in Britain",
    "phonicsHint": "Brit · ain"
  },
  {
    "sourceNo": 8,
    "word": "China",
    "partOfSpeech": "n.",
    "chineseMeaning": "中國",
    "categoryZh": "國家",
    "categoryEn": "Country",
    "englishDefinition": "A large country in Asia.",
    "exampleSentence": "China has many mountains, rivers, and big cities.",
    "phrase": "in China",
    "phonicsHint": "Chi · na"
  },
  {
    "sourceNo": 9,
    "word": "Canada",
    "partOfSpeech": "n.",
    "chineseMeaning": "加拿大",
    "categoryZh": "國家",
    "categoryEn": "Country",
    "englishDefinition": "A large country in North America.",
    "exampleSentence": "Canada has cold winters and many beautiful lakes.",
    "phrase": "in Canada",
    "phonicsHint": "Can · a · da"
  },
  {
    "sourceNo": 10,
    "word": "England",
    "partOfSpeech": "n.",
    "chineseMeaning": "英格蘭",
    "categoryZh": "國家",
    "categoryEn": "Country",
    "englishDefinition": "A country that is part of the United Kingdom.",
    "exampleSentence": "England is famous for London and rainy weather.",
    "phrase": "in England",
    "phonicsHint": "Eng · land"
  },
  {
    "sourceNo": 11,
    "word": "Russia",
    "partOfSpeech": "n.",
    "chineseMeaning": "俄羅斯",
    "categoryZh": "國家",
    "categoryEn": "Country",
    "englishDefinition": "A very large country in Europe and Asia.",
    "exampleSentence": "Russia has long winters and many large forests.",
    "phrase": "in Russia",
    "phonicsHint": "Rus · sia"
  },
  {
    "sourceNo": 12,
    "word": "country",
    "partOfSpeech": "n.",
    "chineseMeaning": "國家",
    "categoryZh": "國家",
    "categoryEn": "Country",
    "englishDefinition": "An area of land with its own government and people.",
    "exampleSentence": "Each country has its own flag and language.",
    "phrase": "each country",
    "phonicsHint": "coun · try"
  },
  {
    "sourceNo": 1,
    "word": "French",
    "partOfSpeech": "adj.; n.",
    "chineseMeaning": "法國的；法國人",
    "categoryZh": "人民/語言",
    "categoryEn": "People / Language",
    "englishDefinition": "From France, or the language spoken in France.",
    "exampleSentence": "We learned a French song in music class.",
    "phrase": "French song",
    "phonicsHint": "Fr + ench"
  },
  {
    "sourceNo": 2,
    "word": "German",
    "partOfSpeech": "adj.; n.",
    "chineseMeaning": "德國的；德國人",
    "categoryZh": "人民/語言",
    "categoryEn": "People / Language",
    "englishDefinition": "From Germany, or the language spoken in Germany.",
    "exampleSentence": "My friend learned a German word yesterday.",
    "phrase": "German word",
    "phonicsHint": "Ger · man"
  },
  {
    "sourceNo": 3,
    "word": "Indian",
    "partOfSpeech": "adj.",
    "chineseMeaning": "印度的；印第安人的",
    "categoryZh": "人民/語言",
    "categoryEn": "People / Language",
    "englishDefinition": "From India, or related to India.",
    "exampleSentence": "We tasted Indian food during culture week.",
    "phrase": "Indian food",
    "phonicsHint": "In · di · an"
  },
  {
    "sourceNo": 4,
    "word": "Japanese",
    "partOfSpeech": "n.; adj.",
    "chineseMeaning": "日本人,日語；日本的",
    "categoryZh": "人民/語言",
    "categoryEn": "People / Language",
    "englishDefinition": "From Japan, or the language spoken in Japan.",
    "exampleSentence": "She wrote a Japanese word on the board.",
    "phrase": "Japanese word",
    "phonicsHint": "Jap · a · nese"
  },
  {
    "sourceNo": 5,
    "word": "Russian",
    "partOfSpeech": "adj.; n.",
    "chineseMeaning": "俄國的; 俄國人（語）",
    "categoryZh": "人民/語言",
    "categoryEn": "People / Language",
    "englishDefinition": "From Russia, or the language spoken in Russia.",
    "exampleSentence": "We saw a Russian dance in the video.",
    "phrase": "Russian dance",
    "phonicsHint": "Rus · sian"
  },
  {
    "sourceNo": 6,
    "word": "American",
    "partOfSpeech": "n.",
    "chineseMeaning": "美國人",
    "categoryZh": "人民/語言",
    "categoryEn": "People / Language",
    "englishDefinition": "A person from the United States.",
    "exampleSentence": "An American student visited our class today.",
    "phrase": "American student",
    "phonicsHint": "A · mer · i · can"
  },
  {
    "sourceNo": 7,
    "word": "Australian",
    "partOfSpeech": "adj.",
    "chineseMeaning": "澳洲(人)的",
    "categoryZh": "人民/語言",
    "categoryEn": "People / Language",
    "englishDefinition": "From Australia, or related to Australia.",
    "exampleSentence": "The Australian flag was on the classroom wall.",
    "phrase": "Australian flag",
    "phonicsHint": "Aus · tra · li · an"
  },
  {
    "sourceNo": 8,
    "word": "British",
    "partOfSpeech": "adj.",
    "chineseMeaning": "英國(人)的",
    "categoryZh": "人民/語言",
    "categoryEn": "People / Language",
    "englishDefinition": "From Britain, or related to Britain.",
    "exampleSentence": "The British teacher told us a funny story.",
    "phrase": "British teacher",
    "phonicsHint": "Brit · ish"
  },
  {
    "sourceNo": 9,
    "word": "Chinese",
    "partOfSpeech": "adj.; n.",
    "chineseMeaning": "中國的；中文",
    "categoryZh": "人民/語言",
    "categoryEn": "People / Language",
    "englishDefinition": "From China, or the language spoken in China.",
    "exampleSentence": "We practiced Chinese writing after lunch today.",
    "phrase": "Chinese writing",
    "phonicsHint": "Chi · nese"
  },
  {
    "sourceNo": 10,
    "word": "Canadian",
    "partOfSpeech": "adj.",
    "chineseMeaning": "加拿大（人）的",
    "categoryZh": "人民/語言",
    "categoryEn": "People / Language",
    "englishDefinition": "From Canada, or related to Canada.",
    "exampleSentence": "A Canadian family moved near our school.",
    "phrase": "Canadian family",
    "phonicsHint": "Ca · na · di · an"
  },
  {
    "sourceNo": 11,
    "word": "English",
    "partOfSpeech": "n.& adj.",
    "chineseMeaning": "英國(的)；英語",
    "categoryZh": "人民/語言",
    "categoryEn": "People / Language",
    "englishDefinition": "The language used in this lesson, or related to England.",
    "exampleSentence": "English class starts right after math today.",
    "phrase": "English class",
    "phonicsHint": "Eng · lish"
  },
  {
    "sourceNo": 12,
    "word": "African",
    "partOfSpeech": "adj.",
    "chineseMeaning": "非洲的，非洲人的",
    "categoryZh": "人民/語言",
    "categoryEn": "People / Language",
    "englishDefinition": "From Africa, or related to Africa.",
    "exampleSentence": "We learned about African music in class.",
    "phrase": "African music",
    "phonicsHint": "Af · ri · can"
  },
  {
    "sourceNo": 1,
    "word": "pocket",
    "partOfSpeech": "n.",
    "chineseMeaning": "口袋",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A small cloth bag in clothes for carrying things.",
    "exampleSentence": "I put my key in my jacket pocket.",
    "phrase": "jacket pocket",
    "phonicsHint": "pock · et"
  },
  {
    "sourceNo": 2,
    "word": "place",
    "partOfSpeech": "n.",
    "chineseMeaning": "地方，地點",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A location or area where something is.",
    "exampleSentence": "This quiet place is good for reading books.",
    "phrase": "quiet place",
    "phonicsHint": "pl + ace"
  },
  {
    "sourceNo": 3,
    "word": "radio",
    "partOfSpeech": "n.",
    "chineseMeaning": "收音機",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A machine that receives sound programs and music.",
    "exampleSentence": "Grandpa listens to the radio every morning.",
    "phrase": "listen to the radio",
    "phonicsHint": "ra · di · o"
  },
  {
    "sourceNo": 4,
    "word": "reader",
    "partOfSpeech": "n.",
    "chineseMeaning": "讀者",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A person who reads books, stories, or articles.",
    "exampleSentence": "A good reader asks questions while reading.",
    "phrase": "good reader",
    "phonicsHint": "read · er"
  },
  {
    "sourceNo": 5,
    "word": "reading",
    "partOfSpeech": "n.",
    "chineseMeaning": "閱讀",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "The activity of looking at and understanding words.",
    "exampleSentence": "Reading before bed helps me learn new words.",
    "phrase": "reading before bed",
    "phonicsHint": "read · ing"
  },
  {
    "sourceNo": 6,
    "word": "closet",
    "partOfSpeech": "n.",
    "chineseMeaning": "壁櫥",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A small room or space for storing clothes and things.",
    "exampleSentence": "I put my coat inside the closet.",
    "phrase": "inside the closet",
    "phonicsHint": "clos · et"
  },
  {
    "sourceNo": 7,
    "word": "road",
    "partOfSpeech": "n.",
    "chineseMeaning": "道路",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A long hard path for cars and buses.",
    "exampleSentence": "The road near our school is very busy.",
    "phrase": "busy road",
    "phonicsHint": "r + oad"
  },
  {
    "sourceNo": 8,
    "word": "roof",
    "partOfSpeech": "n.",
    "chineseMeaning": "屋頂",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "The top cover of a building or house.",
    "exampleSentence": "Rain fell loudly on the metal roof.",
    "phrase": "on the roof",
    "phonicsHint": "r + oof"
  },
  {
    "sourceNo": 9,
    "word": "row",
    "partOfSpeech": "n.",
    "chineseMeaning": "行，排",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A straight line of people or things.",
    "exampleSentence": "We sat in a row during the concert.",
    "phrase": "in a row",
    "phonicsHint": "r + ow"
  },
  {
    "sourceNo": 10,
    "word": "ring",
    "partOfSpeech": "v.; n.",
    "chineseMeaning": "按鈴；鈴聲",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A small round sound, or to make a bell sound.",
    "exampleSentence": "The school bell will ring after lunch.",
    "phrase": "bell will ring",
    "phonicsHint": "r + ing"
  },
  {
    "sourceNo": 11,
    "word": "set",
    "partOfSpeech": "n.",
    "chineseMeaning": "一套",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A group of things that belong together.",
    "exampleSentence": "I bought a set of colored pencils.",
    "phrase": "a set of",
    "phonicsHint": "s + et"
  },
  {
    "sourceNo": 12,
    "word": "seat",
    "partOfSpeech": "n.; v.",
    "chineseMeaning": "座位; 使就座",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A chair or place where someone can sit.",
    "exampleSentence": "Please take a seat near the window.",
    "phrase": "take a seat",
    "phonicsHint": "s + eat"
  },
  {
    "sourceNo": 13,
    "word": "sauce",
    "partOfSpeech": "n.",
    "chineseMeaning": "調味汁, 醬汁",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A thick liquid put on food for flavor.",
    "exampleSentence": "She put tomato sauce on her noodles.",
    "phrase": "tomato sauce",
    "phonicsHint": "s + auce"
  },
  {
    "sourceNo": 14,
    "word": "salt",
    "partOfSpeech": "n.",
    "chineseMeaning": "鹽",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A white substance used to make food taste better.",
    "exampleSentence": "Dad added a little salt to the soup.",
    "phrase": "a little salt",
    "phonicsHint": "s + alt"
  },
  {
    "sourceNo": 15,
    "word": "sheet",
    "partOfSpeech": "n.",
    "chineseMeaning": "床單",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A large piece of cloth used on a bed.",
    "exampleSentence": "Mom changed the bed sheet on Sunday.",
    "phrase": "bed sheet",
    "phonicsHint": "sh + eet"
  },
  {
    "sourceNo": 16,
    "word": "side",
    "partOfSpeech": "n.",
    "chineseMeaning": "一側",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "The left, right, front, or back part of something.",
    "exampleSentence": "Write your name on the left side.",
    "phrase": "left side",
    "phonicsHint": "s + ide"
  },
  {
    "sourceNo": 17,
    "word": "sign",
    "partOfSpeech": "n.",
    "chineseMeaning": "符號",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A mark, picture, or words that give information.",
    "exampleSentence": "The sign says we should walk slowly.",
    "phrase": "road sign",
    "phonicsHint": "s + ign"
  },
  {
    "sourceNo": 18,
    "word": "sport",
    "partOfSpeech": "n.",
    "chineseMeaning": "體育運動",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A game or activity that uses body movement and skill.",
    "exampleSentence": "Basketball is my favorite sport after school.",
    "phrase": "favorite sport",
    "phonicsHint": "sp + ort"
  },
  {
    "sourceNo": 19,
    "word": "stair",
    "partOfSpeech": "n.",
    "chineseMeaning": "臺階",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "One step in a set of steps.",
    "exampleSentence": "Be careful on the wet stair today.",
    "phrase": "wet stair",
    "phonicsHint": "st + air"
  },
  {
    "sourceNo": 20,
    "word": "stamp",
    "partOfSpeech": "n.",
    "chineseMeaning": "郵票",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A small paper mark put on a letter.",
    "exampleSentence": "I put a stamp on the postcard.",
    "phrase": "postage stamp",
    "phonicsHint": "st + amp"
  },
  {
    "sourceNo": 21,
    "word": "step",
    "partOfSpeech": "n.",
    "chineseMeaning": "步驟",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "One action in a process, or one movement of a foot.",
    "exampleSentence": "The first step is to wash your hands.",
    "phrase": "first step",
    "phonicsHint": "st + ep"
  },
  {
    "sourceNo": 22,
    "word": "storm",
    "partOfSpeech": "n.",
    "chineseMeaning": "暴風雨",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "Very bad weather with strong wind, rain, or snow.",
    "exampleSentence": "The storm kept everyone inside after school.",
    "phrase": "big storm",
    "phonicsHint": "st + orm"
  },
  {
    "sourceNo": 23,
    "word": "swimming",
    "partOfSpeech": "n.",
    "chineseMeaning": "游泳",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "The activity of moving through water with your body.",
    "exampleSentence": "Swimming is fun when the water is warm.",
    "phrase": "go swimming",
    "phonicsHint": "swim · ming"
  },
  {
    "sourceNo": 24,
    "word": "tail",
    "partOfSpeech": "n.",
    "chineseMeaning": "尾巴",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "The back part of an animal body.",
    "exampleSentence": "The dog wagged its tail near the door.",
    "phrase": "wag its tail",
    "phonicsHint": "t + ail"
  },
  {
    "sourceNo": 25,
    "word": "taxi",
    "partOfSpeech": "n.",
    "chineseMeaning": "計程車",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A car you pay to ride in.",
    "exampleSentence": "We took a taxi to the airport early.",
    "phrase": "take a taxi",
    "phonicsHint": "tax · i"
  },
  {
    "sourceNo": 26,
    "word": "shampoo",
    "partOfSpeech": "n.",
    "chineseMeaning": "洗髮精",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A liquid soap used for washing hair.",
    "exampleSentence": "I need shampoo to wash my hair tonight.",
    "phrase": "use shampoo",
    "phonicsHint": "sham · poo"
  },
  {
    "sourceNo": 27,
    "word": "choice",
    "partOfSpeech": "n.",
    "chineseMeaning": "選擇",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "The act of choosing between two or more things.",
    "exampleSentence": "You made a good choice for lunch today.",
    "phrase": "good choice",
    "phonicsHint": "ch + oice"
  },
  {
    "sourceNo": 28,
    "word": "team",
    "partOfSpeech": "n.",
    "chineseMeaning": "團隊",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A group of people who work or play together.",
    "exampleSentence": "Our team practiced hard before the game.",
    "phrase": "our team",
    "phonicsHint": "t + eam"
  },
  {
    "sourceNo": 29,
    "word": "telephone",
    "partOfSpeech": "n.",
    "chineseMeaning": "手機",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A device used to talk to someone far away.",
    "exampleSentence": "I called Grandma on the telephone after dinner.",
    "phrase": "on the telephone",
    "phonicsHint": "tel · e · phone"
  },
  {
    "sourceNo": 30,
    "word": "television",
    "partOfSpeech": "n.",
    "chineseMeaning": "電視",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A machine with a screen for watching shows.",
    "exampleSentence": "We watched a nature show on television.",
    "phrase": "on television",
    "phonicsHint": "tel · e · vi · sion"
  },
  {
    "sourceNo": 31,
    "word": "tennis",
    "partOfSpeech": "n.",
    "chineseMeaning": "網球",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A sport played with rackets and a ball.",
    "exampleSentence": "My brother plays tennis every Saturday morning.",
    "phrase": "play tennis",
    "phonicsHint": "ten · nis"
  },
  {
    "sourceNo": 32,
    "word": "toilet",
    "partOfSpeech": "n.",
    "chineseMeaning": "廁所",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A seat used in a bathroom.",
    "exampleSentence": "Please clean the toilet after you use it.",
    "phrase": "clean the toilet",
    "phonicsHint": "toi · let"
  },
  {
    "sourceNo": 33,
    "word": "top",
    "partOfSpeech": "n.",
    "chineseMeaning": "頂端",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "The highest part or surface of something.",
    "exampleSentence": "Put the box on the top shelf.",
    "phrase": "top shelf",
    "phonicsHint": "t + op"
  },
  {
    "sourceNo": 34,
    "word": "towel",
    "partOfSpeech": "n.",
    "chineseMeaning": "毛巾",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A piece of cloth used for drying things.",
    "exampleSentence": "I used a towel after swimming class.",
    "phrase": "use a towel",
    "phonicsHint": "tow · el"
  },
  {
    "sourceNo": 35,
    "word": "town",
    "partOfSpeech": "n.",
    "chineseMeaning": "鎮",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A place where people live, smaller than a city.",
    "exampleSentence": "Our town has a library and park.",
    "phrase": "small town",
    "phonicsHint": "t + own"
  },
  {
    "sourceNo": 36,
    "word": "wave",
    "partOfSpeech": "n.",
    "chineseMeaning": "波浪",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A raised line of water moving across the surface.",
    "exampleSentence": "A big wave came toward the beach.",
    "phrase": "big wave",
    "phonicsHint": "w + ave"
  },
  {
    "sourceNo": 37,
    "word": "weekend",
    "partOfSpeech": "n.",
    "chineseMeaning": "週末",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "Saturday and Sunday, or the end of the week.",
    "exampleSentence": "We visit my grandparents on the weekend.",
    "phrase": "on the weekend",
    "phonicsHint": "week · end"
  },
  {
    "sourceNo": 38,
    "word": "bridge",
    "partOfSpeech": "n.",
    "chineseMeaning": "橋",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A structure built over water, roads, or valleys.",
    "exampleSentence": "The bus crossed the bridge after school.",
    "phrase": "cross the bridge",
    "phonicsHint": "br + idge"
  },
  {
    "sourceNo": 39,
    "word": "brush",
    "partOfSpeech": "n.",
    "chineseMeaning": "刷子",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A tool with hairs used for cleaning or painting.",
    "exampleSentence": "Use a brush to clean your shoes.",
    "phrase": "use a brush",
    "phonicsHint": "br + ush"
  },
  {
    "sourceNo": 40,
    "word": "basket",
    "partOfSpeech": "n.",
    "chineseMeaning": "籃子",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A container used for carrying or holding things.",
    "exampleSentence": "She carried apples in a small basket.",
    "phrase": "small basket",
    "phonicsHint": "bas · ket"
  },
  {
    "sourceNo": 41,
    "word": "bookcase",
    "partOfSpeech": "n.",
    "chineseMeaning": "書櫃",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A piece of furniture used for holding books.",
    "exampleSentence": "The dictionary is on the bookcase shelf.",
    "phrase": "bookcase shelf",
    "phonicsHint": "book · case"
  },
  {
    "sourceNo": 42,
    "word": "season",
    "partOfSpeech": "n.",
    "chineseMeaning": "時期；季節",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "One of the four parts of the year, or a time period.",
    "exampleSentence": "Spring is my favorite season of the year.",
    "phrase": "favorite season",
    "phonicsHint": "sea · son"
  },
  {
    "sourceNo": 43,
    "word": "window",
    "partOfSpeech": "n.",
    "chineseMeaning": "窗戶",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "An opening in a wall with glass for light and air.",
    "exampleSentence": "Please open the window before class starts.",
    "phrase": "open the window",
    "phonicsHint": "win · dow"
  },
  {
    "sourceNo": 44,
    "word": "airport",
    "partOfSpeech": "n.",
    "chineseMeaning": "機場",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A place where airplanes take off and land.",
    "exampleSentence": "We arrived at the airport before sunrise.",
    "phrase": "arrive at the airport",
    "phonicsHint": "air · port"
  },
  {
    "sourceNo": 45,
    "word": "airplane",
    "partOfSpeech": "n.",
    "chineseMeaning": "飛機",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A flying vehicle with wings and engines.",
    "exampleSentence": "The airplane flew above the clouds today.",
    "phrase": "fly an airplane",
    "phonicsHint": "air · plane"
  },
  {
    "sourceNo": 46,
    "word": "autumn",
    "partOfSpeech": "n.",
    "chineseMeaning": "秋天",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "The season after summer and before winter.",
    "exampleSentence": "Leaves turn red and yellow in autumn.",
    "phrase": "in autumn",
    "phonicsHint": "au · tumn"
  },
  {
    "sourceNo": 47,
    "word": "calendar",
    "partOfSpeech": "n.",
    "chineseMeaning": "日曆",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A chart that shows days, weeks, and months.",
    "exampleSentence": "Mark the test date on your calendar.",
    "phrase": "on your calendar",
    "phonicsHint": "cal · en · dar"
  },
  {
    "sourceNo": 48,
    "word": "dish",
    "partOfSpeech": "n.",
    "chineseMeaning": "盤；一道菜",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A plate or a kind of food.",
    "exampleSentence": "This dish has rice, vegetables, and chicken.",
    "phrase": "main dish",
    "phonicsHint": "d + ish"
  },
  {
    "sourceNo": 49,
    "word": "history",
    "partOfSpeech": "n.",
    "chineseMeaning": "歷史",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "Things that happened in the past.",
    "exampleSentence": "We studied ancient history in class today.",
    "phrase": "study history",
    "phonicsHint": "his · to · ry"
  },
  {
    "sourceNo": 50,
    "word": "hospital",
    "partOfSpeech": "n.",
    "chineseMeaning": "醫院",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A place where sick or hurt people get care.",
    "exampleSentence": "My uncle works at the hospital near school.",
    "phrase": "at the hospital",
    "phonicsHint": "hos · pi · tal"
  },
  {
    "sourceNo": 51,
    "word": "hour",
    "partOfSpeech": "n.",
    "chineseMeaning": "小時",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A period of sixty minutes.",
    "exampleSentence": "The movie lasted one hour after dinner.",
    "phrase": "one hour",
    "phonicsHint": "h + our"
  },
  {
    "sourceNo": 52,
    "word": "husband",
    "partOfSpeech": "n.",
    "chineseMeaning": "丈夫",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A married man in relation to his wife.",
    "exampleSentence": "Her husband cooked dinner for the family.",
    "phrase": "her husband",
    "phonicsHint": "hus · band"
  },
  {
    "sourceNo": 53,
    "word": "hotel",
    "partOfSpeech": "n.",
    "chineseMeaning": "旅館，飯店",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A place where people pay to sleep when traveling.",
    "exampleSentence": "We stayed at a hotel near the station.",
    "phrase": "stay at a hotel",
    "phonicsHint": "ho · tel"
  },
  {
    "sourceNo": 54,
    "word": "newspaper",
    "partOfSpeech": "n.",
    "chineseMeaning": "報紙",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A printed paper with news and information.",
    "exampleSentence": "Dad reads the newspaper after breakfast every morning.",
    "phrase": "read the newspaper",
    "phonicsHint": "news · pa · per"
  },
  {
    "sourceNo": 55,
    "word": "neighbour",
    "partOfSpeech": "n.",
    "chineseMeaning": "鄰居",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A person who lives near you.",
    "exampleSentence": "Our neighbour helped us carry the boxes.",
    "phrase": "next-door neighbour",
    "phonicsHint": "neigh · bour"
  },
  {
    "sourceNo": 56,
    "word": "net",
    "partOfSpeech": "n.",
    "chineseMeaning": "網",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A piece of material with holes used to catch or hold things.",
    "exampleSentence": "The ball hit the net during tennis practice.",
    "phrase": "hit the net",
    "phonicsHint": "n + et"
  },
  {
    "sourceNo": 57,
    "word": "nest",
    "partOfSpeech": "n.",
    "chineseMeaning": "(鳥)窩",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "A home that a bird makes for its eggs.",
    "exampleSentence": "We saw a small nest in the tree.",
    "phrase": "bird nest",
    "phonicsHint": "n + est"
  },
  {
    "sourceNo": 58,
    "word": "noon",
    "partOfSpeech": "n.",
    "chineseMeaning": "中午",
    "categoryZh": "名詞",
    "categoryEn": "Noun",
    "englishDefinition": "Twelve o clock in the middle of the day.",
    "exampleSentence": "We eat lunch at noon after English class.",
    "phrase": "at noon",
    "phonicsHint": "n + oon"
  }
];
